version: '3.8'

services:
  hydra-db:
    image: postgres:15
    container_name: hydra-db
    environment:
      POSTGRES_PASSWORD: hydra123
      POSTGRES_DB: hydra
      POSTGRES_USER: hydra
    ports:
      - "5432:5432"
    volumes:
      - hydra_data:/var/lib/postgresql/data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: hydra-n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=hydra123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - hydra-db

volumes:
  hydra_data:
  n8n_data:
