[build]
builder = "nixpacks"

[deploy]
startCommand = "python hydra.py serve"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "hydra-free"
type = "web"
env = "python"
region = "oregon"
plan = "free"
buildCommand = "pip install -r requirements.txt"
startCommand = "python hydra.py serve"

[services.envVars]
PORT = "8000"
